const userActionTypes = {
    SET_TOP_BAR_LOADING: "SET_TOP_BAR_LOADING",
    DROP_TOP_BAR_LOADING: "DROP_TOP_BAR_LOADING",
    SET_PAGE_LOADING: "SET_PAGE_LOADING",
    DROP_PAGE_LOADING: "DROP_PAGE_LOADING",
};

export default userActionTypes;
